[tool.ruff]
line-length = 120           # Sets the maximum line length
target-version = "py311"     # Specifies the target Python version
include = ["*.py", "*.pyi"]  # run ruff only on py files without ipynb

[tool.ruff.lint]
select = [
    "E4", # subset of pypycodestyle
    "E7", # subset of pypycodestyle
    "E9", # subset of pypycodestyle
    "F",  # Pyflakes
    "I",  # isort
]
ignore = ["E402"]

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = ["test_*.py"]
python_functions = ["test_*"]
addopts = "-v --tb=short"

[tool.coverage.run]
source = ["src"]
omit = ["tests/*", "*/__init__.py"]

[tool.coverage.report]
exclude_lines = [
    "pragma: no cover",
    "if __name__ == .__main__.:",
    "raise NotImplementedError",
]
